# Generated by Django 3.1.1 on 2020-09-13 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20200914_0152'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='age',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='details',
            name='comments',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='details',
            name='gender',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='details',
            name='mobile',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='details',
            name='w_mobile',
            field=models.CharField(max_length=50),
        ),
    ]
